path: C:\Users\lukek\College\Capstone\Dataset # dataset root
train: images\train # training images
val: images\valid # validation images

# set all classes
names:
  0: Bear,
  1: Chicken,
  2: Deer,
  3: Lizard,
  4: Pig,
  5: Tiger