path: C:\Users\lukek\College\Capstone\Dataset # dataset root
train: images\train # training images
val: images\train # validation images

# set all classes
names:
  0: Bear,
  1: Deer,
  2: Fox,
  3: Lynx,
  4: Rabbit,