path: C:\Users\lukek\College\Capstone\Dataset # dataset root
train: C:\Users\lukek\College\Capstone\Dataset\Photos\train # training images
val: C:\Users\lukek\College\Capstone\Dataset\Photos\train # validation images

# set all classes
names:
  0: Deer
  1: Duck
  2: Eagle
  3: Horse
  4: Rabbit
  5: Snake
  6: Squirrel